# Generated by Django 5.1.7 on 2025-10-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='anons')),
                ('full_text', models.TextField(verbose_name='Статя')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
